ITEM.name = "AR-C"
ITEM.description = "A sidearm utilising .357 Caliber ammunition."
ITEM.model = "models/weapons/arccw/fml/w_fatcry5_arc.mdl"
ITEM.class = "arccw_fml_blast_fc5_arc"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.exRender = true
ITEM.Ammo = "smg1"